### PR TITLE
adding sidebar for open ai key

### PR DESCRIPTION
**Pull request by TuanaCelik**

### CODE REVIEW

**Review by silvanocerza — APPROVED** [review]
Looks alright to me. 👍

**Comment by TuanaCelik** [comment]
@ZanSara @silvanocerza roland just sent this, which doesn't have any replies, but would be worrying nonetheless
https://discuss.huggingface.co/t/bug-variables-exposed-across-instances/20980

**Comment by silvanocerza** [comment]
That's not good at all. Pretty huge issue. 😅

**Comment by TuanaCelik** [comment]
There's been no reply.. I will reach out to the HuggingFace team. It feels like if this were the case it would have been fixed pretty quickly!

**Pull request merged**
